### ISSUE TITLE
How to solve the "boost.python.argumenterror" problem?

### ISSUE THREAD

**Issue by Sexypanda8888** [kwea123/VTuber_Unity#13]
python demo.py --debug --cpu
 0.042 Traceback (most recent call last):
  File "demo.py", line 219, in <module>
    main()
  File "demo.py", line 116, in main
    right=facebox[2], bottom=facebox[3])
Boost.Python.ArgumentError: Python argument types in
    rectangle.__init__(rectangle)
did not match C++ signature:
    __init__(struct _object * __ptr64, long left, long top, long right, long bottom)
    __init__(struct _object * __ptr64)

I tried to reload my boost but it dosn't work .can you help me ? I 'm so eager to paly with it .

**Comment by Sexypanda8888** [comment]
I finally solve the problem by load another type of dlib
